---
title: "PEAR - Biodiversidade & Ecossistemas"
author: "Felipe & Ivson"
format: html
---

## Carregar dados e blibliotecas

```{r}
data_PE <- read.csv("~/pear/data_PE.csv", dec = ",") # 262mil ocorrencias de todas as espécies

adapta_pe<-read.delim2("~/pear/DadosBiod.csv")

library(geobr)
library(sf)
library(tidyverse)
library(viridis)

```

## Estado de Pernambuco

```{r}

muni_pe <- read_municipality(
  code_muni = "PE", 
  year= 2022,
  showProgress = FALSE
  )

muni_pe<-muni_pe[muni_pe$code_muni != "2605459", ] # retirar Feranndo de Noronha

# plot
ggplot() +
  geom_sf(data=muni_pe, fill="#2D3E50", color="#FEBF57", size=.15, show.legend = FALSE) +
    coord_sf(xlim = c(-42, -34), ylim = c(-7, -10))+
  geom_point(data = data_PE,aes(x=decimalLongitude, y=decimalLatitude),color = "red", alpha = 0.2)+
  theme_minimal()

```


```{r}
## Registros por município

data_PE %>% 
  select(decimalLatitude,decimalLongitude) %>% 
  mutate(id_points = as.character(1:n()))->sp_coord

muni_pe <- st_as_sf(muni_pe, crs = 4326) # convert to sf object
sp_coord<-st_as_sf(data_PE, coords = c( "decimalLongitude", "decimalLatitude"), crs = 4326)
sp_coord <- st_transform(sp_coord, st_crs(muni_pe))

st_crs(sp_coord) # SIRGAS 2000
st_crs(muni_pe)# SIRGAS 2000 As duas OK

sp_coord$geometry # 262.332 pontos
muni_pe$geom # 185 municípios

library(sfhotspot)

sp_counts_mun <- hotspot_count(sp_coord, grid = muni_pe) # Mensagem de aviso: 4,088 point is outside the area covered by the supplied polygons.

sum(sp_counts_mun$n) # 258244 registros

glimpse(sp_counts_mun) # OK para registros

sp_counts_mun %>% 
  mutate(area_muni_km2=st_area(sp_counts_mun$geometry)/1000000) %>% 
  mutate(sp_per_area=n/area_muni_km2) %>% 
  filter(code_muni!= "2605459")->sp_counts_mun




```


```{r}
# Gráficos e Mapas com a base completa biodiversidade

ggplot()+
  geom_sf(data=sp_counts_mun, aes(fill=log(n+1), show.legend = TRUE)) + 
  scale_fill_viridis(name="log(# de registros)")+
  labs(title = "Número de registros no GBIF por km²")
```

## Dados provenientes do Adapta Brasil

```{r}

dados_AB <- read.delim2("~/pear/DadosBiod.csv")
dados_AB %>% 
  rename(code_muni=geocod_ibge) ->dados_AB

dados_comp_geom<-left_join(sp_counts_mun,dados_AB)
## Sensibilidade

dados_comp_geom %>% 
  ggplot()+geom_sf(data=dados_comp_geom, aes(fill=sensib), show.legend = TRUE)+
   scale_fill_viridis(name="valor")+
  labs(title = "Sensibilidade do Bioma")

### 
library(lwgeom) # otimizar junção dos grids

dados_comp_geom %>% 
  st_transform(., crs=4674)

dados_comp_geom %>% 
  group_by(rds) %>%
  summarise(across(geometry, ~ st_combine(.)), .groups = "keep")->geom_rds
  #summarize(geometry = st_union(geometry))->geom_rds
  
ggplot()+
  geom_sf(data=dados_comp_geom, aes(fill=s_luc_2017), show.legend = TRUE)+
  geom_sf(data=geom_rds, alpha=0.1, lwd=1, aes(color=rds))+
  scale_color_brewer(palette = "Set3")+
  scale_fill_viridis(name="valor")+
  labs(title = "Mudança do Uso de Solo")
  
  
```


## Correlações entre índices que compõem Vulnerabilidade
```{r}

library(corrplot)

dados_comp_geom %>% 
  as_tibble() %>% 
  select(sp_count, vuln:v_cap & -geom)->cor_vuln

M<-cor(cor_vuln)
corrplot(M, method="number",type = 'lower', diag = FALSE)


```

## Valores médios de V=S-C+E

```{r}

## Todos os sub-índices

dados_comp_geom %>% 
  as_tibble() %>%
  select(rds, vuln, sensib, v_cap, expos ) %>% 
  pivot_longer(!rds, names_to = "indic") %>%
  group_by(rds, indic) %>% 
  summarise_if(is.numeric, list(mean, sd)) %>% 
  ggplot(aes(rds,fn1, color=indic))+
  geom_point(size=3,position=position_dodge(width=0.7))+
  scale_color_discrete(name= "",labels=c("Exposição", "Sensibilidade", "Capacidade Adaptativa", "Vulnerabilidade"))+
  geom_pointrange(aes(ymin=fn1-fn2, ymax=fn1+fn2),position=position_dodge(width=0.7))+
  coord_flip()+
  theme(legend.position = "top")+
  labs(y="Valor do Índice", x="Região de Desenvolvimento Socioeconômico")->A

A

## Risco climático atual e projetado

dados_comp_geom %>% 
  as_tibble() %>%
  select(rds,risco_atual:risco_SWL2.0) %>% 
  pivot_longer(!rds, names_to = "risco") %>%
  group_by(rds, risco) %>% 
  summarise_if(is.numeric, list(mean, sd)) %>% 
  ggplot(aes(rds,fn1, group=risco, color=risco))+
  geom_point(size=3,position=position_dodge(width=0.7))+
  scale_color_discrete(name= "",labels=c("Risco Atual", "Risco SWL 1.5", "Risco SWL 2.0"))+
  geom_pointrange(aes(ymin=fn1-fn2, ymax=fn1+fn2),position=position_dodge(width=0.7))+
  coord_flip()+
  theme(legend.position = "top")+
  labs(y="Risco Climático", x="Região de Desenvolvimento Socioeconômico")->B
B

## Ameaça à Integridade do Bioma


dados_comp_geom %>% 
  as_tibble() %>%
  select(rds,ameaca_atual:ameaca_SWL2.0) %>% 
  pivot_longer(!rds, names_to = "risco") %>%
  group_by(rds, risco) %>% 
  summarise_if(is.numeric, list(mean, sd)) %>% 
  ggplot(aes(rds,fn1, group=risco, color=risco))+
  geom_point(size=3,position=position_dodge(width=0.7))+
  scale_color_discrete(name= "",labels=c("Ameaça Atual", "Ameaça SWL 1.5", "Ameaça SWL 2.0"))+
  geom_pointrange(aes(ymin=fn1-fn2, ymax=fn1+fn2),position=position_dodge(width=0.7))+
  coord_flip()+
  theme(legend.position = "top")+
  labs(y="Ameaça à Integridade do Bioma", x="Região de Desenvolvimento Socioeconômico")->C

C




```

